### ISSUE TITLE
Class objects returned as nested numpy arrays

### ISSUE THREAD

**Issue by u55** [anntzer/matloader#3]
Hi,

I discovered that a MATLAB class object in a *.mat file is converted to a Numpy structured array nested inside of a regular ndarray of `shape=(1,1)` and `dtype=object`. In order to directly access the structured array, I have to pick the `[0,0]` index of the outer ndarray. Since nested Numpy arrays are almost never made intentionally, I suspect that this a bug. This can be seen with the 'testclass_simple_6.mat' file in the tests/data/ directory.

```python
In [2]: mat = matloader.loadmat('testclass_simple_6.mat')

In [3]: mat['simple'].shape
Out[3]: (1, 1)

In [4]: mat['simple'][0,0].shape
Out[4]: ()

In [5]: type(mat['simple'])
Out[5]: numpy.ndarray

In [6]: type(mat['simple'][0,0])
Out[6]: numpy.void

In [7]: mat['simple']['array_field_2']
Out[7]: array([[array([[ 0.,  1.,  2.,  3.,  4.,  5.]])]], dtype=object)

In [8]: mat['simple'][0,0]['array_field_2']
Out[8]: array([[ 0.,  1.,  2.,  3.,  4.,  5.]])
```

**Comment by anntzer** [comment]
This is intentional.  Say you have a class such as the one defined in `matloader/tests/simpleclass.m`.  Evaluating `[simpleclass simpleclass]` gives you
```
ans = 

  1×2 simpleclass array with properties:

    char_field_1
    array_field_2
    any_field_3
```
i.e. an array of class objects.  So it makes sense to also return class objects in an array, and rely on squeeze_me to, well, squeeze the extra dims.

**Comment by u55** [comment]
Hi Antony,

Please forgive me if I misunderstand; I am not very familiar with MATLAB (which is why I am trying to use python). But it makes sense to me that if MATLAB had saved an array of class instances to a variable in the *.mat file, like in your example above, that matloader would return a python list or a numpy ndarray of `dtype=object` which contains the class instances as individual numpy structured arrays. But if MATLAB had saved a single class instance to a variable in the *.mat file, like in the `'testclass_simple_6.mat'` example, then I would have expected matloader to directly return a single numpy structured array. Is there a reason not to try to make a 1-to-1 mapping of MATLAB types to python types?

At the very least, maybe you could document this behavior in the README since it goes against the principle of least astonishment?

Note that relying on squeeze_me to return a single array leads to some confusing bugs on some array operations using that array, because it is really a nested array and the outer 0-d array has `dtype=object`. For example:

```python
In [3]: mat = matloader.loadmat('testclass_simple_6.mat', squeeze_me=True)

In [4]: mat['simple'][()]['array_field_2'].dtype
Out[4]: dtype('float64')

In [5]: mat['simple']['array_field_2'].dtype
Out[5]: dtype('O')

In [6]: np.cos(mat['simple'][()]['array_field_2'])
Out[6]: 
array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
         0.28366219]])

In [7]: np.cos(mat['simple']['array_field_2'])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-e04392d37ee7> in <module>()
----> 1 np.cos(mat['simple']['array_field_2'])

AttributeError: 'numpy.ndarray' object has no attribute 'cos'
```
which means that I still have to index the outer 0-d array to access the inner array, even when using `squeeze_me=True`. If this is intentional, then perhaps you could mention it in the documentation?

Thanks.

**Comment by anntzer** [comment]
There is no such thing as "single class instance" in MATLAB (and thus in mat files).  Ultimately, there is exactly one variable type, the array, which is necessarily at least two-dimensional (yes, this is a stupid design, but I don't have the choice).  The dtype of the array can be a numeric data type, or a structure, or an classdef type (an "object").  In any case, the variable held is always an array, even if it has a single element.

**Comment by u55** [comment]
I see. Thanks for the explanation.

```matlab
>> x = simpleclass

x = 

  simpleclass with properties:

     char_field_1: 'char_field'
    array_field_2: [0 1 2 3 4 5]
      any_field_3: 0

>> size(x)

ans =

     1     1
```
This was not obvious to me as a newcomer to MATLAB, but I now agree that your choice is indeed the most straightforward 1-to-1 mapping of MATLAB types to Python types.

However, I still think that a few usage examples in the README would prevent the kind of confusing numpy bugs that I showed above. I can put together a short PR for the documentation, if you are interested.

Thanks.

**Comment by anntzer** [comment]
Go for it.
